version: "3.9"

services:
  db-clevertec:
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clevertec
#  web-tomcat:
#    image: tomcat:10.0.27
#    volumes:
#      - ./build/libs/servlet.war:/usr/local/tomcat/webapps/servlet.war
#    ports:
#      - 8080:8080
#    depends_on:
#      - db-clevertec
      