CREATE TABLE IF NOT EXISTS address (
id BIGSERIAL NOT NULL,
postal_code CHARACTER VARYING(9) NOT NULL,
country CHARACTER VARYING(30) NOT NULL,
city CHARACTER VARYING(30) NOT NULL,
street CHARACTER VARYING(30) NOT NULL,
building_number CHARACTER VARYING(7) NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS shop (
id BIGSERIAL NOT NULL,
name CHARACTER VARYING(30) NOT NULL,
address_id BIGINT NOT NULL,
phone CHARACTER VARYING(18) NOT NULL,

PRIMARY KEY(id),

CONSTRAINT fk_address
FOREIGN KEY (address_id)
REFERENCES address (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS product (
id BIGSERIAL NOT NULL,
description CHARACTER VARYING(60) NOT NULL,
is_auction BOOLEAN NOT NULL,

PRIMARY KEY(id),
UNIQUE(description)
);

CREATE TABLE IF NOT EXISTS storage (
id BIGSERIAL NOT NULL,
product_id BIGINT NOT NULL,
unit CHARACTER VARYING(4) NOT NULL DEFAULT 'pcs',
price NUMERIC(11, 2) NOT NULL,
quantity NUMERIC(9, 3) NOT NULL,

PRIMARY KEY(id),

CONSTRAINT fk_product
FOREIGN KEY (product_id)
REFERENCES product (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS discount_card (
id BIGSERIAL NOT NULL,
number CHARACTER VARYING(9) NOT NULL,
discount_value SMALLINT NOT NULL DEFAULT 0,

PRIMARY KEY(id),
UNIQUE(number)
);

CREATE TABLE IF NOT EXISTS seller (
id BIGSERIAL NOT NULL,
name CHARACTER VARYING(30) NOT NULL,
family_name CHARACTER VARYING(40) NOT NULL,
email CHARACTER VARYING(30) NOT NULL,
role CHARACTER VARYING(17) NOT NULL,

PRIMARY KEY(id),
UNIQUE(email)
);
